// A generator to import required OpenGL and its extensions.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Text;

namespace CanDoUrco.OpenGl;

internal static class LibraryImporter
{
    // csharpier-ignore
    public static string GenerateNativeLibraryImporter(string @namespace, string visibility, string glClassName)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated>"                                                                                                 );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("using System.Reflection;"                                                                                            );
        sb.AppendLine("using System.Runtime.InteropServices"                                                                                );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine($"namespace {@namespace};"                                                                                            );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine($"{visibility} static partial class {glClassName}"                                                                    );
        sb.AppendLine("{"                                                                                                                   );
        sb.AppendLine("    private const string DllName = \"OpenGL\";"                                                                      );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("    static Gl() =>"                                                                                                  );
        sb.AppendLine("        NativeLibrary.SetDllImportResolver(Assembly.GetExecutingAssembly(), ResolveOpenGlLibrary);"                  );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("    private sattic nint ResolveOpenGlLibrary(string libraryName, Assembly assembly, DllImportSearchPath? searchPath)");
        sb.AppendLine("    {"                                                                                                               );
        sb.AppendLine("        if (libraryName != DllName)"                                                                                 );
        sb.AppendLine("        {"                                                                                                           );
        sb.AppendLine("             return 0;"                                                                                              );
        sb.AppendLine("        }"                                                                                                           );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("        foearch (var name in Candidates())"                                                                          );
        sb.AppendLine("        {"                                                                                                           );
        sb.AppendLine("            if (NativeLibrary.TryLoad(name, assembly, searchPath, out nint handle))"                                 );
        sb.AppendLine("            {"                                                                                                       );
        sb.AppendLine("                return handle;"                                                                                      );
        sb.AppendLine("            }"                                                                                                       );
        sb.AppendLine("        }"                                                                                                           );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("        return 0;"                                                                                                   );
        sb.AppendLine("    }"                                                                                                               );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("    private static IEnumerable<string> Candidates()"                                                                 );
        sb.AppendLine("    {"                                                                                                               );
        sb.AppendLine("        if (OperatingSystem.IsWindows())"                                                                            );
        sb.AppendLine("        {"                                                                                                           );
        sb.AppendLine("            yield return \"opengl32.dll\";"                                                                          );
        sb.AppendLine("        }"                                                                                                           );
        sb.AppendLine("        else if (OperatingSystem.IsMacOS())"                                                                         );
        sb.AppendLine("        {"                                                                                                           );
        sb.AppendLine("            yield return \"/System/Library/Frameworks/OpenGL.framework/OpenGL\";"                                    );
        sb.AppendLine("        }"                                                                                                           );
        sb.AppendLine("        else if (OperatingSystem.IsLinux() || OperatingSystem.IsFreeBSD())"                                          );
        sb.AppendLine("        {"                                                                                                           );
        sb.AppendLine("            yield return \"libOpenGL.so.0\";"                                                                        );
        sb.AppendLine("            yield return \"libGL.so.1\";"                                                                            );
        sb.AppendLine("            yield return \"libGL.so\";"                                                                              );
        sb.AppendLine("        }"                                                                                                           );
        sb.AppendLine(                                                                                                                      );
        sb.AppendLine("        throw new PlatformNotSupportedException();"                                                                  );
        sb.AppendLine("    }"                                                                                                               );
        sb.AppendLine("}"                                                                                                                   );
        sb.AppendLine(                                                                                                                      );

        return sb.ToString();
    }
}
