// A generator for loading OpenGL libraries.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License

namespace CanDoUrco.OpenGl.Generator;

internal static class Attributes
{
    public const string AttributeMetadataName = "CanDoUrco.OpenGl.Generator.OpenGlAttribute";

    public static string Generate() =>
        """
            // <auto-generated/>
            #nullable enable
            using System;

            namespace CanDoUrco.OpenGl.Generator
            {
                internal enum OpenGlProfile
                {
                    Core,
                    Compatibility,
                    ES,
                }

                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                internal sealed class OpenGlAttribute : Attribute
                {
                    public OpenGlAttribute(string versionOrExtension)
                    {
                        VersionOrExtension = versionOrExtension;
                    }

                    public string VersionOrExtension { get; }

                    public OpenGlProfile Profile { get; set; } = OpenGlProfile.Core;

                    public string? LoaderMethod { get; set; }
                }
            }
            """;
}
