// A generator for loading OpenGL libraries.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License

namespace CanDoUrco.OpenGL.Generator;

internal static class GLAttributes
{
    public const string AttributeMetadataName = "CanDoUrco.OpenGL.Generator.OpenGLAttribute";
    public const string ExtensionAttributeMetadataName =
        "CanDoUrco.OpenGL.Generator.OpenGLExtensionAttribute";

    public static string Generate() =>
        """
            // <auto-generated/>
            #nullable enable
            using System;

            namespace CanDoUrco.OpenGL.Generator
            {
                /// <summary>
                /// Represents the different OpenGL profiles.
                /// </summary>
                internal enum OpenGLProfile
                {
                    /// <summary>
                    /// The core profile.
                    /// </summary>
                    Core,

                    /// <summary>
                    /// The compatibility profile.
                    /// </summary>
                    Compatibility,

                    /// <summary>
                    /// The OpenGL ES profile.
                    /// </summary>
                    ES,
                }

                /// <summary>
                /// Represents an OpenGL version requirement for a class.
                /// </summary>
                /// <remarks>
                /// This attribute should be applied to partial, static classes that require a specific OpenGL version.
                /// </remarks>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
                internal sealed class OpenGLAttribute : Attribute
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="OpenGLAttribute"/> class with the specified OpenGL version.
                    /// </summary>
                    /// <param name="major">The major version number.</param>
                    /// <param name="minor">The minor version number.</param>
                    public OpenGLAttribute(int major, int minor)
                    {
                        Version = new Version(major, minor);
                    }

                    /// <summary>
                    /// Gets the OpenGL version required by the class.
                    /// </summary>
                    public Version Version { get; }

                    /// <summary>
                    /// Gets or sets the OpenGL profile required by the class.
                    /// </summary>
                    public OpenGLProfile Profile { get; set; } = OpenGLProfile.Core;

                    /// <summary>
                    /// Gets or sets the name of the method used to load the OpenGL functions.
                    /// </summary>
                    public string? LoaderMethod { get; set; }
                }

                /// <summary>
                /// Represents an OpenGL extension requirement for a class.
                /// </summary>
                /// <remarks>
                /// This attribute should be applied to partial, static classes that require a specific OpenGL extension.
                /// </remarks>
                [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
                internal sealed class OpenGLExtensionAttribute : Attribute
                {
                    /// <summary>
                    /// Initializes a new instance of the <see cref="OpenGLExtensionAttribute"/> class with the specified OpenGL extension.
                    /// </summary>
                    /// <param name="extension">The name of the OpenGL extension.</param>
                    public OpenGLExtensionAttribute(string extension)
                    {
                        Extension = extension;
                    }

                    /// <summary>
                    /// Gets the name of the OpenGL extension required by the class.
                    /// </summary>
                    public string Extension { get; }
                }
            }
            """;
}
