// A generator for loading OpenGL libraries.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License

using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace CanDoUrco.OpenGL.Generator;

internal static class GLEmitter
{
    private const string Loader = "global::CanDoUrco.OpenGL.Generator.OpenGLLibraryLoader";
    private const string Marshal = "global::System.Runtime.InteropServices.Marshal";

    private enum Kind
    {
        Value,
        Enum,
        Bool,
        Ref,
        In,
        Span,
        ReadOnlySpan,
        GenericSpan,
        GenericReadOnlySpan,
        Pointer,
        String,
        StringArray,
        Hidden,
    }

    private sealed class Param
    {
        public ParamDef Def { get; set; } = default!;
        public string Name { get; set; } = default!;
        public string Local { get; set; } = default!;
        public string Raw { get; set; } = default!;
        public Kind Kind { get; set; } = Kind.Value;
        public string Element { get; set; } = "";
        public string PublicType { get; set; } = "";
        public string? EnumType { get; set; }
        public string? LengthSource { get; set; }
        public string? GenericName { get; set; }
    }

    public static string Emit(GLTarget target, GLRegistry registry, GLSelection selection)
    {
        var enumDefs = new Dictionary<string, EnumDef>();
        foreach (var name in selection.Enums)
        {
            if (!registry.Enums.TryGetValue(name, out var candidates))
            {
                continue;
            }

            enumDefs[name] =
                candidates.FirstOrDefault(c => c.Api == selection.Api)
                ?? candidates.FirstOrDefault(c => c.Api is null)
                ?? candidates[0];
        }

        var groups = new SortedDictionary<string, List<EnumDef>>(StringComparer.Ordinal);
        var ungrouped = new List<EnumDef>();
        foreach (var def in enumDefs.Values)
        {
            if (def.Groups.Length == 0)
            {
                ungrouped.Add(def);
                continue;
            }

            foreach (var group in def.Groups)
            {
                if (!groups.TryGetValue(group, out var list))
                {
                    groups[group] = list = [];
                }

                list.Add(def);
            }
        }

        var enumTypes = groups.Keys.ToDictionary(g => g, EnumTypeName);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591, CS8981, CA1707, CA1008");
        sb.AppendLine();
        var indent = 0;
        if (target.Namespace is not null)
        {
            sb.AppendLine($"namespace {target.Namespace}");
            sb.AppendLine("{");
            indent++;
        }

        foreach (var container in target.Containers)
        {
            Line(sb, indent, container);
            Line(sb, indent, "{");
            indent++;
        }

        Line(
            sb,
            indent,
            $"{target.Accessibility} {(target.IsStatic ? "static " : "")}partial class {target.Name}"
        );

        Line(sb, indent, "{");
        indent++;

        if (ungrouped.Count > 0)
        {
            EmitEnum(sb, indent, "Ungrouped", ungrouped, false);
        }

        foreach (var pair in groups)
        {
            EmitEnum(sb, indent, pair.Key, pair.Value, registry.BitmaskGroups.Contains(pair.Key));
        }

        var emittedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var name in selection.Commands.OrderBy(n => n, StringComparer.Ordinal))
        {
            if (registry.Commands.TryGetValue(name, out var command))
            {
                EmitCommand(sb, indent, command, enumTypes, emittedNames, target.LoaderMethod);
            }
        }

        indent--;
        Line(sb, indent, "}");
        foreach (var _ in target.Containers)
        {
            indent--;
            Line(sb, indent, "}");
        }

        if (target.Namespace is not null)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private static void Line(StringBuilder sb, int indent, string text)
    {
        if (text.Length == 0)
        {
            sb.AppendLine();
            return;
        }

        sb.Append(' ', indent * 4).AppendLine(text);
    }

    private static string EnumTypeName(string group)
    {
        var chars = group.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray();
        var name = new string(chars);
        if (name.Length == 0 || char.IsDigit(name[0]))
        {
            name = "_" + name;
        }

        return char.ToUpperInvariant(name[0]) + name.Substring(1) + "Enum";
    }

    private static string MemberName(string glName)
    {
        var name = glName.StartsWith("GL_", StringComparison.Ordinal)
            ? glName.Substring(3)
            : glName;

        var sb = new StringBuilder();
        foreach (var token in name.Split(['_'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (char.IsDigit(token[0]))
            {
                sb.Append(token.ToUpperInvariant());
            }
            else
            {
                sb.Append(char.ToUpperInvariant(token[0]))
                    .Append(token.Substring(1).ToLowerInvariant());
            }
        }

        var result = sb.ToString();
        if (result.Length == 0 || char.IsDigit(result[0]))
        {
            result = "_" + result;
        }

        return result;
    }

    private static (string Type, bool Signed) ConstType(IEnumerable<EnumDef> defs)
    {
        var min = defs.Min(d => d.Value);
        var max = defs.Max(d => d.Value);
        if (min < 0)
        {
            return min >= int.MinValue && max <= int.MaxValue ? ("int", true) : ("long", true);
        }

        return max > uint.MaxValue ? ("ulong", false) : ("uint", false);
    }

    private static string Literal(decimal value, string type)
    {
        if (value < 0)
        {
            return value.ToString(CultureInfo.InvariantCulture);
        }

        var hex = "0x" + ((ulong)value).ToString("X", CultureInfo.InvariantCulture);
        return type switch
        {
            "ulong" => hex + "UL",
            "uint" => hex + "U",
            _ => hex,
        };
    }

    private static void EmitEnum(
        StringBuilder sb,
        int indent,
        string group,
        List<EnumDef> defs,
        bool isBitmask
    )
    {
        var typeName = EnumTypeName(group);
        var underlying = group == "Boolean" ? "byte" : ConstType(defs).Type;
        Line(sb, indent, "");
        if (isBitmask)
        {
            Line(sb, indent, "[global::System.Flags]");
        }

        Line(sb, indent, $"public enum {typeName} : {underlying}");
        Line(sb, indent, "{");
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var def in defs.OrderBy(d => d.Value).ThenBy(d => d.Name, StringComparer.Ordinal))
        {
            var member = MemberName(def.Name);
            if (used.Add(member))
            {
                Line(sb, indent + 1, $"{member} = {Literal(def.Value, underlying)},");
            }
        }

        Line(sb, indent, "}");
    }

    private static string MapType(string glType) =>
        glType switch
        {
            "GLenum" or "GLbitfield" or "GLuint" or "GLhandleARB" => "uint",
            "GLboolean" or "GLubyte" or "GLchar" or "GLcharARB" => "byte",
            "GLbyte" => "sbyte",
            "GLshort" => "short",
            "GLushort" or "GLhalf" or "GLhalfARB" or "GLhalfNV" => "ushort",
            "GLint" or "GLsizei" or "GLclampx" or "GLfixed" => "int",
            "GLfloat" or "GLclampf" => "float",
            "GLdouble" or "GLclampd" => "double",
            "GLint64" or "GLint64EXT" => "long",
            "GLuint64" or "GLuint64EXT" => "ulong",
            _ => "nint",
        };

    private static string Escape(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None ? "@" + name : name;

    private static string RawParamType(ParamDef def) =>
        def.Depth > 0 || def.BaseType == "void" ? "nint" : MapType(def.BaseType);

    private static bool IsEnumCandidate(ParamDef def, Dictionary<string, string> enumTypes) =>
        def.Depth == 0
        && def.Group is not null
        && enumTypes.ContainsKey(def.Group)
        && def.BaseType is "GLenum" or "GLbitfield";

    private static bool IsArray(ParamDef def) => def.Len is not null && def.Len != "1";

    private static void EmitCommand(
        StringBuilder sb,
        int indent,
        CommandDef command,
        Dictionary<string, string> enumTypes,
        HashSet<string> emittedNames,
        string? loaderMethod
    )
    {
        var methodName = command.Name.StartsWith("gl", StringComparison.Ordinal)
            ? command.Name.Substring(2)
            : command.Name;

        if (methodName.Length == 0 || !emittedNames.Add(methodName))
        {
            return;
        }

        var delegateName = methodName + "Delegate";
        var fieldName =
            "_" + char.ToLowerInvariant(methodName[0]) + methodName.Substring(1) + "Pointer";

        var parameters = command
            .Parameters.Select(p => new Param
            {
                Def = p,
                Name = Escape(p.Name),
                Local = "__" + p.Name,
                Raw = RawParamType(p),
            })
            .ToList();

        Classify(parameters, enumTypes);

        var returnDef = command.Return;
        var rawReturn =
            returnDef.BaseType == "void" && returnDef.Depth == 0 ? "void" : RawParamType(returnDef);

        var publicReturn = rawReturn;
        var returnIsString = false;
        var returnIsBool = false;
        string? returnEnum = null;
        if (rawReturn != "void")
        {
            if (
                returnDef.Depth == 1
                && returnDef.IsConst
                && returnDef.BaseType is "GLubyte" or "GLchar" or "GLcharARB"
            )
            {
                publicReturn = "string?";
                returnIsString = true;
            }
            else if (returnDef.Depth == 0 && returnDef.BaseType == "GLboolean")
            {
                publicReturn = "bool";
                returnIsBool = true;
            }
            else if (IsEnumCandidate(returnDef, enumTypes))
            {
                returnEnum = enumTypes[returnDef.Group!];
                publicReturn = returnEnum;
            }
        }

        Line(sb, indent, "");
        var delegateParams = string.Join(", ", parameters.Select(p => $"{p.Raw} {p.Name}"));
        Line(sb, indent, $"private delegate {rawReturn} {delegateName}({delegateParams});");
        Line(sb, indent, $"private static {delegateName}? {fieldName};");

        var hasGeneric = parameters.Any(p =>
            p.Kind is Kind.GenericSpan or Kind.GenericReadOnlySpan
        );

        EmitMethod(
            sb,
            indent,
            methodName,
            delegateName,
            fieldName,
            command.Name,
            parameters,
            publicReturn,
            returnIsString,
            returnIsBool,
            returnEnum,
            rawReturn,
            loaderMethod
        );

        if (hasGeneric)
        {
            foreach (
                var p in parameters.Where(p =>
                    p.Kind is Kind.GenericSpan or Kind.GenericReadOnlySpan
                )
            )
            {
                p.Kind = Kind.Pointer;
                p.PublicType = "nint";
                p.GenericName = null;
            }

            EmitMethod(
                sb,
                indent,
                methodName,
                delegateName,
                fieldName,
                command.Name,
                parameters,
                publicReturn,
                returnIsString,
                returnIsBool,
                returnEnum,
                rawReturn,
                loaderMethod
            );
        }
    }

    private static void Classify(List<Param> parameters, Dictionary<string, string> enumTypes)
    {
        var genericIndex = 0;
        foreach (var p in parameters)
        {
            var def = p.Def;
            if (def.Depth == 0)
            {
                if (def.BaseType == "GLboolean")
                {
                    p.Kind = Kind.Bool;
                    p.PublicType = "bool";
                }
                else if (IsEnumCandidate(def, enumTypes))
                {
                    p.Kind = Kind.Enum;
                    p.EnumType = enumTypes[def.Group!];
                    p.PublicType = p.EnumType;
                }
                else
                {
                    p.PublicType = p.Raw;
                }

                continue;
            }

            var isChar = def.BaseType is "GLchar" or "GLcharARB";
            var isArray = IsArray(def);
            if (def.Depth == 1 && def.BaseType == "void")
            {
                if (isArray)
                {
                    p.GenericName = "T" + genericIndex++;
                    p.Kind = def.IsConst ? Kind.GenericReadOnlySpan : Kind.GenericSpan;
                    p.PublicType = (def.IsConst ? "ReadOnlySpan<" : "Span<") + p.GenericName + ">";
                    p.PublicType = "global::System." + p.PublicType;
                    p.Element = p.GenericName;
                }
                else
                {
                    p.Kind = Kind.Pointer;
                    p.PublicType = "nint";
                }
            }
            else if (def.Depth == 1 && isChar && def.IsConst && def.Len is null)
            {
                p.Kind = Kind.String;
                p.PublicType = "string?";
            }
            else if (def.Depth == 2 && isChar && def.IsConst)
            {
                p.Kind = Kind.StringArray;
                p.PublicType = "string[]";
            }
            else if (def.Depth <= 2)
            {
                p.Element =
                    def.Depth == 2 ? "nint"
                    : def.BaseType == "GLboolean" ? "bool"
                    : MapType(def.BaseType);
                if (isArray)
                {
                    p.Kind = def.IsConst ? Kind.ReadOnlySpan : Kind.Span;
                    p.PublicType =
                        $"global::System.{(def.IsConst ? "ReadOnlySpan" : "Span")}<{p.Element}>";
                }
                else
                {
                    p.Kind = def.IsConst ? Kind.In : Kind.Ref;
                    p.PublicType = $"{(def.IsConst ? "in" : "ref")} {p.Element}";
                }
            }
            else
            {
                p.Kind = Kind.Pointer;
                p.PublicType = "nint";
            }
        }

        foreach (
            var array in parameters.Where(p =>
                p.Kind is Kind.Span or Kind.ReadOnlySpan or Kind.StringArray
            )
        )
        {
            var target = parameters.FirstOrDefault(p =>
                p.Def.Name == array.Def.Len && p.Kind == Kind.Value && p.Def.Depth == 0
            );
            if (target is not null && target.Raw is "int" or "uint" or "long" or "ulong" or "nint")
            {
                target.Kind = Kind.Hidden;
                target.LengthSource = $"({target.Raw}){array.Name}.Length";
            }
        }
    }

    private static void EmitMethod(
        StringBuilder sb,
        int indent,
        string methodName,
        string delegateName,
        string fieldName,
        string nativeName,
        List<Param> parameters,
        string publicReturn,
        bool returnIsString,
        bool returnIsBool,
        string? returnEnum,
        string rawReturn,
        string? loaderMethod
    )
    {
        var loaderArgument = loaderMethod is null ? "" : ", " + loaderMethod;
        var visible = parameters.Where(p => p.Kind != Kind.Hidden).ToList();
        var generics = visible
            .Where(p => p.GenericName is not null)
            .Select(p => p.GenericName!)
            .ToList();

        var needsUnsafe = parameters.Any(p =>
            p.Kind
                is Kind.Ref
                    or Kind.In
                    or Kind.Span
                    or Kind.ReadOnlySpan
                    or Kind.GenericSpan
                    or Kind.GenericReadOnlySpan
                    or Kind.StringArray
        );

        var signature = string.Join(", ", visible.Select(p => $"{p.PublicType} {p.Name}"));
        var typeParams = generics.Count > 0 ? $"<{string.Join(", ", generics)}>" : "";

        Line(
            sb,
            indent,
            $"public static {(needsUnsafe ? "unsafe " : "")}{publicReturn} {methodName}{typeParams}({signature})"
        );

        if (generics.Count > 0)
        {
            foreach (var g in generics)
            {
                Line(sb, indent + 1, $"where {g} : unmanaged");
            }
        }

        Line(sb, indent, "{");
        var body = indent + 1;
        Line(
            sb,
            body,
            $"{fieldName} ??= {Loader}.LoadMethod<{delegateName}>(\"{nativeName}\"{loaderArgument});"
        );

        var strings = parameters.Where(p => p.Kind is Kind.String).ToList();
        var stringArrays = parameters.Where(p => p.Kind is Kind.StringArray).ToList();
        var hasCleanup = strings.Count > 0 || stringArrays.Count > 0;
        foreach (var s in strings)
        {
            Line(sb, body, $"nint {s.Local} = 0;");
        }

        foreach (var a in stringArrays)
        {
            Line(sb, body, $"var {a.Local}Strings = new nint[{a.Name}.Length];");
        }

        var inner = body;
        if (hasCleanup)
        {
            Line(sb, body, "try");
            Line(sb, body, "{");
            inner++;
            foreach (var s in strings)
            {
                Line(sb, inner, $"{s.Local} = {Marshal}.StringToCoTaskMemUTF8({s.Name});");
            }

            foreach (var a in stringArrays)
            {
                Line(sb, inner, $"for (var i = 0; i < {a.Name}.Length; i++)");
                Line(sb, inner, "{");
                Line(
                    sb,
                    inner + 1,
                    $"{a.Local}Strings[i] = {Marshal}.StringToCoTaskMemUTF8({a.Name}[i]);"
                );

                Line(sb, inner, "}");
                Line(sb, inner, "");
            }
        }

        var depth = inner;
        foreach (var p in parameters)
        {
            string? pin = p.Kind switch
            {
                Kind.Ref or Kind.In => $"{p.Element}* {p.Local} = &{p.Name}",
                Kind.Span or Kind.ReadOnlySpan or Kind.GenericSpan or Kind.GenericReadOnlySpan =>
                    $"{p.Element}* {p.Local} = {p.Name}",
                Kind.StringArray => $"nint* {p.Local} = {p.Local}Strings",
                _ => null,
            };

            if (pin is null)
            {
                continue;
            }

            Line(sb, depth, $"fixed ({pin})");
            Line(sb, depth, "{");
            depth++;
        }

        var args = string.Join(
            ", ",
            parameters.Select(p =>
                p.Kind switch
                {
                    Kind.Enum => $"({p.Raw}){p.Name}",
                    Kind.Bool => $"(byte)({p.Name} ? 1 : 0)",
                    Kind.Hidden => p.LengthSource!,
                    Kind.String => p.Local,
                    Kind.Ref
                    or Kind.In
                    or Kind.Span
                    or Kind.ReadOnlySpan
                    or Kind.GenericSpan
                    or Kind.GenericReadOnlySpan
                    or Kind.StringArray => $"(nint){p.Local}",
                    _ => p.Name,
                }
            )
        );

        var call = $"{fieldName}({args})";
        if (rawReturn == "void")
        {
            Line(sb, depth, $"{call};");
        }
        else if (returnIsString)
        {
            Line(sb, depth, $"return {Marshal}.PtrToStringUTF8({call});");
        }
        else if (returnIsBool)
        {
            Line(sb, depth, $"return {call} != 0;");
        }
        else if (returnEnum is not null)
        {
            Line(sb, depth, $"return ({returnEnum}){call};");
        }
        else
        {
            Line(sb, depth, $"return {call};");
        }

        while (depth > inner)
        {
            depth--;
            Line(sb, depth, "}");
        }

        if (hasCleanup)
        {
            Line(sb, body, "}");
            Line(sb, body, "finally");
            Line(sb, body, "{");
            foreach (var s in strings)
            {
                Line(sb, body + 1, $"{Marshal}.FreeCoTaskMem({s.Local});");
            }

            foreach (var a in stringArrays)
            {
                Line(sb, body + 1, $"foreach (var ptr in {a.Local}Strings)");
                Line(sb, body + 1, "{");
                Line(sb, body + 2, $"{Marshal}.FreeCoTaskMem(ptr);");
                Line(sb, body + 1, "}");
            }

            Line(sb, body, "}");
        }

        Line(sb, indent, "}");
    }
}
