// A generator for loading OpenGL libraries.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License

namespace CanDoUrco.OpenGl.Generator;

internal static class LibraryLoader
{
    public static string Generate() =>
        $$"""
            // <auto-generated/>
            #nullable enable
            using System;
            using System.Collections.Generic;
            using System.Runtime.InteropServices;

            namespace CanDoUrco.OpenGl.Generator
            {
                internal static class OpenGlLibraryLoader
                {
                    {{GenerateLibraryLoader()}}

                    {{GenerateEnumerateLibraries()}}
                }
            }
            """;

    private static string GenerateLibraryLoader() =>
        """
            public static Func<string, nint>? ProcAddressLoader { get; set; }

            public static T LoadMethod<T>(string methodName, Func<string, nint>? procAddressLoader = null)
                where T : Delegate
            {
                ArgumentException.ThrowIfNullOrEmpty(methodName);
                foreach (var library in EnumerateLibraries())
                {
                    if (string.IsNullOrEmpty(library))
                    {
                        continue;
                    }

                    if (!NativeLibrary.TryLoad(library, out var handle))
                    {
                        continue;
                    }

                    if (!NativeLibrary.TryGetExport(handle, methodName, out var functionPointer))
                    {
                        continue;
                    }

                    return Marshal.GetDelegateForFunctionPointer<T>(functionPointer);
                }

                var loader = procAddressLoader ?? ProcAddressLoader;
                if (loader is not null)
                {
                    var address = loader(methodName);
                    if (address > 3 && address != -1)
                    {
                        return Marshal.GetDelegateForFunctionPointer<T>(address);
                    }
                }

                throw new EntryPointNotFoundException(
                    $"Unable to load method '{methodName}' from the OpenGL library or the proc address loader."
                );
            }
            """;

    private static string GenerateEnumerateLibraries() =>
        """
            private static IEnumerable<string> EnumerateLibraries()
                    {
                        if (OperatingSystem.IsWindows())
                        {
                            yield return "opengl32.dll";
                        }
                        else if (OperatingSystem.IsMacOS())
                        {
                            yield return "/System/Library/Frameworks/OpenGL.framework/OpenGL";
                        }
                        else if (OperatingSystem.IsLinux())
                        {
                            yield return "libOpenGL.so.0";
                            yield return "libOpenGL.so";
                            yield return "libEGL.so.1";
                            yield return "libEGL.so";
                            yield return "libGL.so.1";
                            yield return "libGL.so";
                        }
                        else
                        {
                            throw new PlatformNotSupportedException(RuntimeInformation.OSDescription);
                        }
                    }
            """;
}
