// This is a small testing ground for CanDoUrco.
// Copyright (C) 2026  Can Do Urco (Victor Matia-Cheng)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY, without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

namespace CanDoUrco.Glfw.Input;

/// <summary>
/// A list of supported keys.
/// </summary>
public enum GlfwKey
{
    /// <summary>
    /// For keys that are not known to this list.
    /// </summary>
    Unknown = Native.Glfw.KeyUnknownDefine,
    Space = Native.Glfw.KeySpaceDefine,
    Apostrophe = Native.Glfw.KeyApostropheDefine,
    Comma = Native.Glfw.KeyCommaDefine,
    Minus = Native.Glfw.KeyMinusDefine,
    Period = Native.Glfw.KeyPeriodDefine,
    Slash = Native.Glfw.KeySlashDefine,
    Number0 = Native.Glfw.Key0Define,
    Number1 = Native.Glfw.Key1Define,
    Number2 = Native.Glfw.Key2Define,
    Number3 = Native.Glfw.Key3Define,
    Number4 = Native.Glfw.Key4Define,
    Number5 = Native.Glfw.Key5Define,
    Number6 = Native.Glfw.Key6Define,
    Number7 = Native.Glfw.Key7Define,
    Number8 = Native.Glfw.Key8Define,
    Number9 = Native.Glfw.Key9Define,
    Semicolon = Native.Glfw.KeySemicolonDefine,
    Equal = Native.Glfw.KeyEqualDefine,
    A = Native.Glfw.KeyADefine,
    B = Native.Glfw.KeyBDefine,
    C = Native.Glfw.KeyCDefine,
    D = Native.Glfw.KeyDDefine,
    E = Native.Glfw.KeyEDefine,
    F = Native.Glfw.KeyFDefine,
    G = Native.Glfw.KeyGDefine,
    H = Native.Glfw.KeyHDefine,
    I = Native.Glfw.KeyIDefine,
    J = Native.Glfw.KeyJDefine,
    K = Native.Glfw.KeyKDefine,
    L = Native.Glfw.KeyLDefine,
    M = Native.Glfw.KeyMDefine,
    N = Native.Glfw.KeyNDefine,
    O = Native.Glfw.KeyODefine,
    P = Native.Glfw.KeyPDefine,
    Q = Native.Glfw.KeyQDefine,
    R = Native.Glfw.KeyRDefine,
    S = Native.Glfw.KeySDefine,
    T = Native.Glfw.KeyTDefine,
    U = Native.Glfw.KeyUDefine,
    V = Native.Glfw.KeyVDefine,
    W = Native.Glfw.KeyWDefine,
    X = Native.Glfw.KeyXDefine,
    Y = Native.Glfw.KeyYDefine,
    Z = Native.Glfw.KeyZDefine,
    LeftBracket = Native.Glfw.KeyLeftBracketDefine,
    Backslash = Native.Glfw.KeyBackslashDefine,
    RightBracket = Native.Glfw.KeyRightBracketDefine,
    GraveAccent = Native.Glfw.KeyGraveAccentDefine,
    World1 = Native.Glfw.KeyWorld1Define,
    World2 = Native.Glfw.KeyWorld2Define,
    Escape = Native.Glfw.KeyEscapeDefine,
    Enter = Native.Glfw.KeyEnterDefine,
    Tab = Native.Glfw.KeyTabDefine,
    Backspace = Native.Glfw.KeyBackspaceDefine,
    Insert = Native.Glfw.KeyInsertDefine,
    Delete = Native.Glfw.KeyDeleteDefine,
    Right = Native.Glfw.KeyRightDefine,
    Left = Native.Glfw.KeyLeftDefine,
    Down = Native.Glfw.KeyDownDefine,
    Up = Native.Glfw.KeyUpDefine,
    PageUp = Native.Glfw.KeyPageUpDefine,
    PageDown = Native.Glfw.KeyPageDownDefine,
    Home = Native.Glfw.KeyHomeDefine,
    End = Native.Glfw.KeyEndDefine,
    CapsLock = Native.Glfw.KeyCapsLockDefine,
    ScrollLock = Native.Glfw.KeyScrollLockDefine,
    NumLock = Native.Glfw.KeyNumLockDefine,
    PrintScreen = Native.Glfw.KeyPrintScreenDefine,
    Pause = Native.Glfw.KeyPauseDefine,
    F1 = Native.Glfw.KeyF1Define,
    F2 = Native.Glfw.KeyF2Define,
    F3 = Native.Glfw.KeyF3Define,
    F4 = Native.Glfw.KeyF4Define,
    F5 = Native.Glfw.KeyF5Define,
    F6 = Native.Glfw.KeyF6Define,
    F7 = Native.Glfw.KeyF7Define,
    F8 = Native.Glfw.KeyF8Define,
    F9 = Native.Glfw.KeyF9Define,
    F10 = Native.Glfw.KeyF10Define,
    F11 = Native.Glfw.KeyF11Define,
    F12 = Native.Glfw.KeyF12Define,
    F13 = Native.Glfw.KeyF13Define,
    F14 = Native.Glfw.KeyF14Define,
    F15 = Native.Glfw.KeyF15Define,
    F16 = Native.Glfw.KeyF16Define,
    F17 = Native.Glfw.KeyF17Define,
    F18 = Native.Glfw.KeyF18Define,
    F19 = Native.Glfw.KeyF19Define,
    F20 = Native.Glfw.KeyF20Define,
    F21 = Native.Glfw.KeyF21Define,
    F22 = Native.Glfw.KeyF22Define,
    F23 = Native.Glfw.KeyF23Define,
    F24 = Native.Glfw.KeyF24Define,
    F25 = Native.Glfw.KeyF25Define,
    Keypad0 = Native.Glfw.KeyKeypad0Define,
    Keypad1 = Native.Glfw.KeyKeypad1Define,
    Keypad2 = Native.Glfw.KeyKeypad2Define,
    Keypad3 = Native.Glfw.KeyKeypad3Define,
    Keypad4 = Native.Glfw.KeyKeypad4Define,
    Keypad5 = Native.Glfw.KeyKeypad5Define,
    Keypad6 = Native.Glfw.KeyKeypad6Define,
    Keypad7 = Native.Glfw.KeyKeypad7Define,
    Keypad8 = Native.Glfw.KeyKeypad8Define,
    Keypad9 = Native.Glfw.KeyKeypad9Define,
    KeypadDecimal = Native.Glfw.KeyKeypadDecimalDefine,
    KeypadDivide = Native.Glfw.KeyKeypadDivideDefine,
    KeypadMultiply = Native.Glfw.KeyKeypadMultiplyDefine,
    KeypadSubtract = Native.Glfw.KeyKeypadSubtractDefine,
    KeypadAdd = Native.Glfw.KeyKeypadAddDefine,
    KeypadEnter = Native.Glfw.KeyKeypadEnterDefine,
    KeypadEqual = Native.Glfw.KeyKeypadEqualDefine,
    LeftShift = Native.Glfw.KeyLeftShiftDefine,
    LeftControl = Native.Glfw.KeyLeftControlDefine,
    LeftAlt = Native.Glfw.KeyLeftAltDefine,
    LeftSuper = Native.Glfw.KeyLeftSuperDefine,
    RightShift = Native.Glfw.KeyRightShiftDefine,
    RightControl = Native.Glfw.KeyRightControlDefine,
    RightAlt = Native.Glfw.KeyRightAltDefine,
    RightSuper = Native.Glfw.KeyRightSuperDefine,
    Menu = Native.Glfw.KeyMenuDefine,
}
