// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

namespace CanDoUrco.Glfw.Input;

/// <summary>
/// A class that represents the state of a gamepad.
/// </summary>
/// <remarks>This class is sealed.</remarks>
public sealed class GlfwGamepadState
{
    /// <summary>
    /// Gets the gamepad's button states.
    /// </summary>
    /// <remarks>This collection is always <c>15</c> elements when generated by <see cref="GlfwJoystick.GetGamepadState"/>.</remarks>
    public required IReadOnlyCollection<GlfwGamepadButtonState> Buttons { get; init; }

    /// <summary>
    /// Gets the gamepad's axes values.
    /// </summary>
    /// <remarks>This collection is always <c>6</c> elements when generated by <see cref="GlfwJoystick.GetGamepadState"/>.</remarks>
    public required IReadOnlyCollection<float> Axes { get; init; }
}
