<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <Optimize>false</Optimize>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DefineConstants>$(DefineConstants);RELEASE</DefineConstants>
    <DebugType>none</DebugType>
    <Optimize>true</Optimize>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CanDoUrco.Glfw/CanDoUrco.Glfw.csproj" />
    <ProjectReference Include="../CanDoUrco.IO/CanDoUrco.IO.csproj" />
    <ProjectReference Include="../CanDoUrco.Utilities/CanDoUrco.Utilities.csproj" />
    <ProjectReference
      Include="../CanDoUrco.OpenGL.Generator/CanDoUrco.OpenGL.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Shaders\Core.Vertex.glsl" />
    <EmbeddedResource Include="Resources\Shaders\Core.Fragment.glsl" />
    <EmbeddedResource Include="Resources\Textures\Wall.jpg" />
  </ItemGroup>
</Project>
