<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../CanDoUrco.Glfw/CanDoUrco.Glfw.csproj" />
    <ProjectReference Include="../CanDoUrco.Graphics/CanDoUrco.Graphics.csproj" />
    <ProjectReference Include="../CanDoUrco.IO/CanDoUrco.IO.csproj" />
    <ProjectReference Include="../CanDoUrco.Utilities/CanDoUrco.Utilities.csproj" />
    <ProjectReference
      Include="../CanDoUrco.OpenGL.Generator/CanDoUrco.OpenGL.Generator.csproj"
      OutputItemType="Analyzer"
      ReferenceOutputAssembly="false"
    />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\Shaders\Vertex.glsl" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Resources\Shaders\Fragment.glsl" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
